### ISSUE TITLE
Should fail the handshake when version_info.chosen_version doesn't match long_header.version

### ISSUE THREAD

**Issue by anrossi** [quicwg/version-negotiation#129]
Currently at [section 3](https://datatracker.ietf.org/doc/html/draft-ietf-quic-version-negotiation#section-3) says future versions might allow the long header version to be different from the chosen version in the version_info transport parameter.  But there's nothing about what to do until such a version exists which changes the semantics of the chosen_version.
This is in the initial packet, before incompatible version negotiation, and before compatible version negotiation, has happened.

Which error should the handshake be closed with? [Section 4](https://datatracker.ietf.org/doc/html/draft-ietf-quic-version-negotiation#section-4) says that version info transport parameter parsing errors should use the transport parameter error.

**Comment by DavidSchinazi** [comment]
Thinking about this some more, I think draft-ietf-quic-version-negotiation doesn't need to say anything more, as those details are specific to the compatibility version document. So I opened https://github.com/quicwg/quic-v2/issues/76 to discuss this there.

**Comment by anrossi** [comment]
I'm a little confused because this document explains which errors should be used with QUIC v1 when closing the connection on failure to parse the transport parameter or invalid versions (i.e. 0). In the absence of another compatibility version document, shouldn't this document specify the error for QUIC v1?  Or are you saying this is not an error in QUIC v1, but could be an error in, e.g., QUIC v2?

**Comment by DavidSchinazi** [comment]
This only causes an error when there are two versions involved - and therefore that scenario should be covered by the document that defines compatibility between those two versions. Or do you have a scenario in mind where one version is QUICv1 and the other is unknown?

I'm noticing that RFC 9000 doesn't say what you're supposed to do if you receive a packet from another version - I think the assumption is that you silently drop it because you don't know how to parse it.

**Comment by martinduke** [comment]
Agreed that I should specify the v1/v2 case. But perhaps the VN draft should handle the behavior when the long header has a known version (certainly v1) and the Chosen Version is unknown?

(I imagine that allowing this allows us to have a backdoor for version upgrade if the version field ossifies)

**Comment by martinduke** [comment]
I would recommend that a server sends a VN packet in this case, and a client kills the connection -- there is no valid reason for the server to slip in a version the client didn't advertise.

**Comment by DavidSchinazi** [comment]
Rereading what @anrossi originally wrote along with @martinduke's comments, I think we can tighten up the validation requirements in this spec to prevent tampering. I've written it up as #131, please take a look.

@martinduke I went with forcing a close instead of your suggestion, because this back door would weaken the protocol (allows tampering) without helping (if the long header ossifies we can use compatible VN as our backdoor).

**Comment by martinduke** [comment]
I'm not sure compatible VN is sufficient. If someone writes a firewall that says "drop all Long Headers with version == 4" I don't see that compatible negotiation solves the problem -- all the long headers have to say v1 and the actual negotiation happens using TPs.

Though I haven't fully thought this through, and certainly not any backdoor implications.

**Comment by DavidSchinazi** [comment]
Note that the requirement is only for the client's first flight. So you work around that firewall by defining v1-to-v4 compatibility as always setting Version=1 in long headers

**Comment by martinduke** [comment]
Yeah, I think that works.
