### ISSUE TITLE
Could this use ALPN identifiers instead?

### ISSUE THREAD

**Issue by martinthomson** [quicwg/version-negotiation#30]
This is likely a big ticket question, and I predict that Ekr will disagree with me here, but it needs to be asked.  In [draft-thomson-tls-snip](https://datatracker.ietf.org/doc/draft-thomson-tls-snip/) I proposed a design that would allow incompatible versions to be authenticated using ALPN identifiers alone.  A similar thing would work here if we were able to guarantee that an application protocol could be used with exactly one QUIC version.

That is not an unreasonable constraint if you consider the interaction between QUIC and other points in the space (Alt-Svc and SVCB in particular both use only ALPN).

FWIW, I want an actual decision about this to be recorded.  We keep agreeing to disagree in other places about this issue and I'm tired of it.  It means that we have one set of assumptions for some protocols and a different set of assumptions for others and the edges don't line up very well at all.  For instance, we might not even need compatible version negotiation if we could agree one way or other.

**Comment by DavidSchinazi** [comment]
I definitely think that we should agree as a community on what ALPN means. I my opinion, Alt-Svc shouldn't have used ALPN, because of all the confusions you describe, but here we are. I don't think this is in-scope for draft-ietf-quic-version-negotiation though, because ALPN is not a QUIC invariant. There are deployed versions of QUIC that do not have a concept of ALPN. Because of this, I think that draft-ietf-quic-version-negotiation should stick to 32bit QUIC versions and leave the ALPN problem alone.

**Comment by DavidSchinazi** [comment]
There was consensus at the last interim meeting to stick with 32bit versions, so I'm closing this. Please comment if you disagree.
