### ISSUE TITLE
Should the client communicate version preference ordering?

### ISSUE THREAD

**Issue by DavidSchinazi** [quicwg/version-negotiation#43]
In #42, @martinthomson mentioned that having the client communicate preference ordering between compatible versions isn't absolutely necessary. This issue tracks whether we want to keep this ordering or not.

**Comment by mjoras** [comment]
During the IETF QUIC WG meeting there was (weak-ish) consensus that this useful to keep.

**Comment by MikeBishop** [comment]
The strongest argument against this was that it doesn't give the server a full ordering, because it doesn't tell the server where the offered version falls in the preference list.  There's a possible answer to that, which is that the client should only offer compatible versions which are more preferred than the currently offered version.

However, we should explicitly state that the server makes the actual decision and MAY factor client preferences into that.  I suspect most won't.

**Comment by DavidSchinazi** [comment]
@MikeBishop that's incorrect. The offered version is present in the list.

**Comment by MikeBishop** [comment]
Ah, thanks for correcting me.  Then we're spending bytes to repeat the version number, which we don't expect servers will typically use.  Not the end of the world either way.

**Comment by LPardue** [comment]
Consensus established. Closing this issue with no action.
